[app]
interval = 5000 # Frontend poller interval (env: APP_INTERVAL)
reload_browser = true # Reload frontend on changes (env: APP_RELOAD_BROWSER)

[server]
port = 3210 # Server listen port (required) (env: SERVER_PORT)

[static]
base = "some/path" # Where to look for assets (required) (env: STATIC_BASE)
index = "index.html" # Fallback path if the requested asset is not found (env: STATIC_INDEX)

# A map from file extensions to content types (env: STATIC_TYPES=css:text/css,...)
[static.types]
"css" = "text/css"
"html" = "text/html"
"ico" = "image/x-icon"
"js" = "text/javascript"
"woff" = "font/woff"
"woff2" = "font/woff2"
"png" = "image/png"
"svg" = "image/svg+xml"

# If this section is defined, assets can be reloaded with an HTTP request to the server
[static.reloader]
method = "PATCH" # HTTP method used to trigger reload (env: STATIC_RELOADER_METHOD)
path = "static" # Reload trigger path (env: STATIC_RELOADER_PATH)

[gzip]
threshold = 350 # Gzip assets that have a byte size above this threshold (env: GZIP_THRESHOLD)

# Content types to gzip (env: GZIP_TYPES=text/html,...)
types = [
  "text/html",
  "text/css",
  "text/javascript",
  "application/json",
  "image/svg+xml"
]
