[static.types]
"css" = "text/css"
"html" = "text/html"
"ico" = "image/x-icon"
"js" = "text/javascript"
"png" = "image/png"
"svg" = "image/svg+xml"
"woff" = "font/woff"
"woff2" = "font/woff2"

[gzip]
threshold = 350
types = [
  "application/json",
  "image/svg+xml",
  "text/css",
  "text/html",
  "text/javascript",
]
