name = "vvv"
version = "1.0.0"

[dependencies]
gleam_crypto = "~> 0.3"
gleam_erlang = "~> 0.18"
gleam_http = "~> 3.1"
gleam_otp = "~> 0.5"
gleam_stdlib = "~> 0.28"
gleam_json = "~> 0.5"
tomerl = "~> 0.5"
mist = "~> 0.11"
nakai = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.10"
