name = "vvv"
version = "1.0.0"

[dependencies]
gleam_crypto = "~> 0.3"
gleam_erlang = "~> 0.19"
gleam_http = "~> 3.4"
gleam_otp = "~> 0.6"
gleam_stdlib = "~> 0.30"
gleam_json = "~> 0.5"
tomerl = "~> 0.5"
mist = "~> 0.13"
nakai = "~> 0.8"
hackney = "~> 1.18"

[dev-dependencies]
gleeunit = "~> 0.10"
